name: "Feature-Request"
description: "Use this template to suggest new enhancements or features."
title: "[Enhancements]"
labels: 
  - "enhancement"
assignees:
  - ahesh001
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the enhancement suggestion! We'll review it as soon as we can.
  - type: input
    id: contact
    attributes:
      label: "Contact Details"
      description: "How can we get in touch with you if we need more info?"
      placeholder: "ex. email@example.com"
    validations:
      required: false
  - type: textarea
    id: feature_request_problem
    attributes:
      label: "Is your feature request related to a problem? Please describe"
      description: "Also tell us why you suggested this feature request."
    validations:
      required: false
  - type: textarea
    id: alternatives_considered
    attributes:
      label: "Describe alternatives you've considered"
      description: "Add any other context or screenshots about the feature request here."
    validations:
      required: false
